# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 2.0"

BOX_IMAGE = "generic/ubuntu2204"

Vagrant.configure("2") do |config|

  config.vm.define "server" do |bs|
    bs.vm.hostname = "server"
    bs.vm.box = BOX_IMAGE
    #bs.vm.network "private_network", ip: "10.0.0.20"
    bs.vm.provider "libvirt" do |libvirt|
      # vb.name = "dev_vm_garr"
      #vb.memory = "2048"
      libvirt.driver = "kvm"
      #libvirt.connect_via_ssh = false
      #libvirt.storage_pool_name = "default"
    end
  end
  
  # Ensure that all Vagrant machines will use the same SSH key pair.
  config.ssh.insert_key = false

  # Enable provisioning with ansible
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    #ansible.install_mode = "pip3"
    #ansible.version = "latest"
    ansible.playbook = "playbook.yml"
    ansible.config_file = "ansible.cfg"
   # ansible.verbose = "vvv"
    ansible.groups = {
      "test" => ["server"]
    }
    #ansible.vault_password_file = ".vault.pwd"
    #ansible.tags = "docker"
    #ansible.tags = "nfs,kube"
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']

  end

end
